require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
project './PaliWallet.xcodeproj'
platform :ios, '12.4' #min_ios_version_supported
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

def react_native_post_install(installer)
    projects = installer.aggregate_targets
      .map{ |t| t.user_project }
      .uniq{ |p| p.path }
      .push(installer.pods_project)

    arm_value = `/usr/sbin/sysctl -n hw.optional.arm64 2>&1`.to_i

    projects.each do |project|
      project.build_configurations.each do |config|
        if arm_value == 1 then
          config.build_settings.delete("EXCLUDED_ARCHS[sdk=iphonesimulator*]")
        else
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
      end

      project.save()
    end
  end

target 'PaliWallet' do
  config = use_native_modules!
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Flags change depending on the env values.
  flags = get_default_flags()
  
  flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  
  end
  
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pod 'CryptoSwift', '~> 1.0'
  
  pod 'UMCPush'
end
